<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="4" hostname="DESKTOP-BR3APVB" failures="2" tests="2" name="Test(failed)" time="0.162" errors="0" timestamp="2023-02-04T09:47:33 IST">
  <testcase classname="failedrerun.FailedDemo2" name="test5" time="0.032">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at failedrerun.FailedDemo2.test5(FailedDemo2.java:18)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- test5 -->
  <testcase classname="failedrerun.FailedDemo1" name="test2" time="0.009">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at failedrerun.FailedDemo1.test2(FailedDemo1.java:19)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
  <testcase classname="failedrerun.FailedDemo2" name="test6" time="0.0">
    <ignored/>
  </testcase> <!-- test6 -->
  <testcase classname="failedrerun.FailedDemo2" name="test4" time="0.0">
    <ignored/>
  </testcase> <!-- test4 -->
  <testcase classname="failedrerun.FailedDemo1" name="test3" time="0.0">
    <ignored/>
  </testcase> <!-- test3 -->
  <testcase classname="failedrerun.FailedDemo1" name="test1" time="0.0">
    <ignored/>
  </testcase> <!-- test1 -->
</testsuite> <!-- Test(failed) -->
